# Generated by Django 3.1.2 on 2020-10-27 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propType', models.CharField(choices=[('CA', 'Casa'), ('DP', 'Departamento')], max_length=2, verbose_name='Tipo Propiedad')),
                ('operation', models.CharField(choices=[('AL', 'Alquiler'), ('VE', 'Venta')], max_length=2, verbose_name='Tipo Operacion')),
                ('description', models.TextField(max_length=200, verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, null=True, upload_to='propiedad', verbose_name='Imagen')),
                ('rooms', models.IntegerField(verbose_name='Habitaciones')),
                ('bathrooms', models.IntegerField(verbose_name='Baños')),
                ('surfice', models.IntegerField(verbose_name='Superficie')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'propiedad',
                'verbose_name_plural': 'propiedades',
                'ordering': ['-created'],
            },
        ),
    ]
