# Generated by Django 3.1.2 on 2020-10-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propiedad',
            options={'ordering': ['-created'], 'verbose_name': 'propiedad', 'verbose_name_plural': 'propiedades'},
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='propType',
            field=models.CharField(choices=[('CA', 'Casa'), ('DP', 'Departamento')], max_length=2, verbose_name='Tipo Propiedad'),
        ),
    ]
