# Generated by Django 3.1.2 on 2020-10-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0002_auto_20201015_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='bathrooms',
            field=models.IntegerField(verbose_name='Baños'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='operation',
            field=models.CharField(choices=[('AL', 'Alquiler'), ('VE', 'Venta')], max_length=2, verbose_name='Tipo Operacion'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='rooms',
            field=models.IntegerField(verbose_name='Habitaciones'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='surfice',
            field=models.IntegerField(verbose_name='Superficie'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
    ]
