# Generated by Django 3.1.2 on 2020-10-28 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0002_auto_20201027_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='user',
            new_name='agente',
        ),
    ]
