# Generated by Django 3.1.2 on 2020-11-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0003_auto_20201028_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='sold_out',
            field=models.BooleanField(default=False, verbose_name='Vendida'),
        ),
    ]
