# Generated by Django 3.1.2 on 2020-10-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0003_auto_20201015_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
    ]
