# Generated by Django 3.1.2 on 2020-10-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0004_auto_20201015_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='propiedad', verbose_name='Imagen'),
        ),
    ]
