# Generated by Django 3.1.2 on 2020-11-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0004_propiedad_sold_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Promocionada'),
        ),
    ]
