# Generated by Django 3.1.2 on 2020-11-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0005_propiedad_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='reserved',
            field=models.BooleanField(default=False, verbose_name='Reservada'),
        ),
    ]
