# Generated by Django 3.1.2 on 2020-11-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20201101_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vendida'),
        ),
    ]
