# Generated by Django 3.1.2 on 2020-11-19 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_auto_20201119_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='completed_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Completada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completada'),
        ),
    ]
