# Generated by Django 3.1.2 on 2020-11-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_auto_20201119_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completada'),
        ),
    ]
